### ISSUE TITLE
Community Contribution - BKdilse

### ISSUE THREAD

**Issue by BKdilse** [EquilibriaCC/EquilibriaCommunityContent#2]
**Content Type**
Remote Node

**Credit**
BKdilse

**Target (written) (can be multiple)**
Node Link

**Content**
xeq.gntl.uk:9231

**Equilibria Address**
Tsz4ouwL1N4EKA8DYw7ssW6eFCsgFudsSNE67R6Z81WE9G3B1QEiHS5hC5QuBRKM2w9m2UZMe5qiJTcVu9edPGka6WKX45zWGU

**Comment by HarrisonHesslink** [comment]
Paid
