### ISSUE TITLE
Community Contribution - EdiZ

### ISSUE THREAD

**Issue by fastnodeeu** [EquilibriaCC/EquilibriaCommunityContent#3]
**Content Type**
Remote Node
**Credit**
EdiZ
**Target** (written) (can be multiple)
Node Link
**Content**
equilibria.fastnode.eu:9231
**Equilibria Address**
Tw1fW6r61Yrc4vMgdEASVBZNRKXRuuBeYb7fD3BR1aac7gr7WZCq7jsJU8x9LEj8XKVRiFRS6gBCjSBCGYDjkDjs1YYDLTf1T

**Comment by HarrisonHesslink** [comment]
Paid
