### ISSUE TITLE
Hard Fork Blog Update

### ISSUE THREAD

**Issue by USCMig** [EquilibriaCC/EquilibriaCommunityContent#4]
**Content Type**: 
Blog
**Credit**:
USCMigs
**Target**:
https://medium.com/coinmonks/equilibria-xeq-protocol-updates-8a2da4c7751c
**Address**:
Tsz5Bpfg412hTNe8Z6ikmERjwKbjyPogr1Nk5H9aFtnBdLd7QnkV9MqH9UFWoPxd9UKreYNpbxcGHLfkawLcKwka4vHhA8rJaN

**Comment by HarrisonHesslink** [comment]
Paid
