### ISSUE TITLE
Remote Node

### ISSUE THREAD

**Issue by GreggyGB** [EquilibriaCC/EquilibriaCommunityContent#5]
Content Type
Remote Node
Credit
GreggyGB
Target (written) (can be multiple)
Node Link
Content
xeq.supporters.ml
Equilibria Address
TvzA6EBMyGwLPiKaYwFYQ8JsMuepejpsTMQXdupKLNWEfEYbEt4jRvrXadWKapi1TBD2W1BGLJpPV3tun9WwqURk1ytPkAEiT

**Comment by HarrisonHesslink** [comment]
Paid
